apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
      - name: java-project
        image: nitesh09nck/java-project:latest
        ports:
        - containerPort: 8080

