name: Java CI/CD with K8s Autoscaling

on:
  push:
    branches:
      - main   # Ensure no extra spaces after '- main'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build app
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Build Docker image
      - name: Build Docker image
        run: docker build -t nitesh09nck/java-project:latest .

      # Login to Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Push image
      - name: Push Docker image
        run: docker push nitesh09nck/java-project:latest

      # Set up Minikube (optional for local testing)
      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      # Apply K8s configs (Deployment, Service, HPA)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml

      # Verify
      - name: Verify Pods and Service
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get hpa

